# Run tests against developer push

# Runs jobs on linux and windows to maintain compatibility.
# The main repo is checked out into a sub-directory because an optional
# second repo may be checked out for testing.

name: pr-test

on:
  push:
    branches-ignore: [ master, main ]

jobs:
  build-test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # job level env vars used for a couple of steps
    env:
      # see github-glue.test.ts for info on setting these
      GGG_TOKEN: ${{ secrets.GGG_TOKEN }}
      GGG_REPOSITORY: ${{ secrets.GGG_REPOSITORY }}
      GGG_WF: "'gitgitgadget.wf=1'"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '${{ matrix.node-version }}' # optional, default is 10.x

    - name: Install packages
      run: npm ci

    - name: Set git test repo config
      shell: bash
      run: echo "::set-env name=GGG_REPO::'gitgitgadget.githubtest.githubuser=$GITHUB_REPOSITORY_OWNER' 'gitgitgadget.$GITHUB_REPOSITORY_OWNER.githubrepo=$GGG_REPOSITORY' 'gitgitgadget.$GITHUB_REPOSITORY_OWNER.githubtoken=$GGG_TOKEN'"
      if: env.GGG_TOKEN

    - name: Run tests
      env:
        GIT_CONFIG_PARAMETERS: ${{ env.GGG_WF }} ${{ secrets.GGG_SMTP_USER }} ${{ secrets.GGG_SMTP_PASS }} ${{ secrets.GGG_SMTP_HOST }} ${{ secrets.GGG_SMTP_OPTS }} ${{ env.GGG_REPO }}
      run: echo $GIT_CONFIG_PARAMETERS
